/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as CustomerSupportRouteImport } from './routes/customer.support'
import { Route as CustomerNotificationsRouteImport } from './routes/customer.notifications'
import { Route as CustomerBookingsRouteImport } from './routes/customer.bookings'
import { Route as CustomerTrackIdRouteImport } from './routes/customer.track.$id'
import { Route as CustomerBookServiceRouteImport } from './routes/customer.book.$service'

const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerSupportRoute = CustomerSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerBookingsRoute = CustomerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerTrackIdRoute = CustomerTrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerBookServiceRoute = CustomerBookServiceRouteImport.update({
  id: '/book/$service',
  path: '/book/$service',
  getParentRoute: () => CustomerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer/': typeof CustomerIndexRoute
  '/customer/book/$service': typeof CustomerBookServiceRoute
  '/customer/track/$id': typeof CustomerTrackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer': typeof CustomerIndexRoute
  '/customer/book/$service': typeof CustomerBookServiceRoute
  '/customer/track/$id': typeof CustomerTrackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer/': typeof CustomerIndexRoute
  '/customer/book/$service': typeof CustomerBookServiceRoute
  '/customer/track/$id': typeof CustomerTrackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer'
    | '/customer/bookings'
    | '/customer/notifications'
    | '/customer/support'
    | '/customer/'
    | '/customer/book/$service'
    | '/customer/track/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer/bookings'
    | '/customer/notifications'
    | '/customer/support'
    | '/customer'
    | '/customer/book/$service'
    | '/customer/track/$id'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/customer/bookings'
    | '/customer/notifications'
    | '/customer/support'
    | '/customer/'
    | '/customer/book/$service'
    | '/customer/track/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRoute: typeof CustomerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/support': {
      id: '/customer/support'
      path: '/support'
      fullPath: '/customer/support'
      preLoaderRoute: typeof CustomerSupportRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/bookings': {
      id: '/customer/bookings'
      path: '/bookings'
      fullPath: '/customer/bookings'
      preLoaderRoute: typeof CustomerBookingsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/track/$id': {
      id: '/customer/track/$id'
      path: '/track/$id'
      fullPath: '/customer/track/$id'
      preLoaderRoute: typeof CustomerTrackIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/book/$service': {
      id: '/customer/book/$service'
      path: '/book/$service'
      fullPath: '/customer/book/$service'
      preLoaderRoute: typeof CustomerBookServiceRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface CustomerRouteChildren {
  CustomerBookingsRoute: typeof CustomerBookingsRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerSupportRoute: typeof CustomerSupportRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerBookServiceRoute: typeof CustomerBookServiceRoute
  CustomerTrackIdRoute: typeof CustomerTrackIdRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerBookingsRoute: CustomerBookingsRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerSupportRoute: CustomerSupportRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerBookServiceRoute: CustomerBookServiceRoute,
  CustomerTrackIdRoute: CustomerTrackIdRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRoute: CustomerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
